### ISSUE TITLE
The generated folder structure are not compatible with jbake

### ISSUE THREAD

**Issue by gilbertoca** [Fisiu/exitwp#1]
Hi,
Just tried it at my blog and found that the generated folder structure are not compatible with JBake and there is no jbake.properties file. I've got this one:

```
gilberto.andrade@A37710:~/tmp/git_working_copy/exitwp/build/jbake/blog.gilbertoca.com$ ll
total 32
drwxr-x---  6 gilberto.andrade users  4096 Fev  6 16:23 ./
drwxr-x---  3 gilberto.andrade users  4096 Fev  6 16:22 ../
drwxr-x---  2 gilberto.andrade users  4096 Fev  6 16:22 about/
drwxr-x--- 29 gilberto.andrade users  4096 Fev  6 16:27 images/
drwxr-x---  2 gilberto.andrade users  4096 Fev  6 16:23 maven/
drwxr-x---  2 gilberto.andrade users 12288 Fev  6 16:27 _posts/

gilberto.andrade@A37710:~/tmp/git_working_copy/exitwp/build/jbake/blog.gilbertoca.com$ jbake 
JBake v2.3.2 (2014-09-21 01:47:44AM) [http://jbake.org]

java.lang.Exception: Error: Required folder cannot be found! Expected to find [template.folder] at: /home/gilberto.andrade/tmp/git_working_copy/exitwp/build/jbake/blog.gilbertoca.com/templates
        at org.jbake.app.Oven.setupRequiredFolderFromConfig(Oven.java:110)
        at org.jbake.app.Oven.setupPaths(Oven.java:94)
        at org.jbake.launcher.Main.bake(Main.java:39)
        at org.jbake.launcher.Main.run(Main.java:77)
        at org.jbake.launcher.Main.main(Main.java:33)
```

I know I can just create a new folder and initialize it with JBake, after that copy the content, but it would be good to see this tool work for JBake like it work for Jekyll. Let me know if you need any information to make it work.
Regards

**Comment by Fisiu** [comment]
Hi,
sorry for late reply. I used it a year ago, only once to just "exit" from wordpress ;-)
I'm not sure how I handled with templates then. As possible solution, we could just download some default template and extract it into templates directory just like jbake -i does.

If you have other idea, please share it with me ;-)

**Comment by Fisiu** [comment]
@kardhen, maybe junior job? Just to improve your python/git skill ;-)
